version: '3'

services:
  backend:
    build:
      context: ./backend
    image: portfolio-backend
    container_name: portfolio-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: portfolio-frontend
    container_name: portfolio-frontend
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env
    restart: unless-stopped