#!/usr/bin/env bash
set -euo pipefail

SNAPSHOT_PATH="${1:-/tmp/static_content_snapshot}"

if [ ! -s "$SNAPSHOT_PATH" ]; then
  exit 0
fi

node -e 'const fs=require("node:fs");const path=process.argv[1];const raw=fs.readFileSync(path,"utf8");let parsed;try{parsed=JSON.parse(raw);}catch{console.error("Invalid STATIC_CONTENT_SNAPSHOT_JSON: not valid JSON");process.exit(1);}if(!parsed||typeof parsed!=="object"||Array.isArray(parsed)){console.error("Invalid STATIC_CONTENT_SNAPSHOT_JSON: expected object envelope");process.exit(1);}for(const key of ["brandingLockup","greeting","cvExperience"]){if(!(key in parsed)||!parsed[key]||typeof parsed[key]!=="object"||Array.isArray(parsed[key])){console.error(`Invalid STATIC_CONTENT_SNAPSHOT_JSON: missing ${key}`);process.exit(1);}}const requireNonEmptyString=(value,label)=>{if(typeof value!=="string"||value.trim().length===0){console.error(`Invalid STATIC_CONTENT_SNAPSHOT_JSON: missing ${label}`);process.exit(1);}};const requireArray=(value,label)=>{if(!Array.isArray(value)){console.error(`Invalid STATIC_CONTENT_SNAPSHOT_JSON: missing ${label}`);process.exit(1);}};requireNonEmptyString(parsed.brandingLockup.activeRoleTitle,"brandingLockup.activeRoleTitle");requireNonEmptyString(parsed.brandingLockup.activeRoleTitleClassName,"brandingLockup.activeRoleTitleClassName");requireNonEmptyString(parsed.greeting.introHtml,"greeting.introHtml");requireNonEmptyString(parsed.greeting.bodyHtml,"greeting.bodyHtml");requireNonEmptyString(parsed.cvExperience.summaryHtml,"cvExperience.summaryHtml");requireNonEmptyString(parsed.cvExperience.coreStrengthsHtml,"cvExperience.coreStrengthsHtml");requireNonEmptyString(parsed.cvExperience.experienceSectionHeading,"cvExperience.experienceSectionHeading");requireArray(parsed.cvExperience.experienceItems,"cvExperience.experienceItems");requireNonEmptyString(parsed.cvExperience.recentIndependentStudySectionHeading,"cvExperience.recentIndependentStudySectionHeading");requireArray(parsed.cvExperience.recentIndependentStudyItems,"cvExperience.recentIndependentStudyItems");' "$SNAPSHOT_PATH"
